
# Attach the library
library(ggplot2)

# We will need this so we can use the pipe: %>%
library(magrittr)

# Read in metadata TSV file
metadata <- readr::read_tsv(metadata_file)


# Read in data TSV file
df <- readr::read_tsv(data_file) %>%
  # Tuck away the gene ID column as row names, leaving only numeric values
  tibble::column_to_rownames("Gene")
  
  
# Make the sure the columns (samples) are in the same order as the metadata
df <- df %>%
  dplyr::select(metadata$refinebio_accession_code)

# Check if this is in the same order
all.equal(colnames(df), metadata$refinebio_accession_code)

# Perform Principal Component Analysis (PCA) using the `prcomp()` function
pca <- prcomp(
  t(df), # transpose our data frame to obtain PC scores for samples, not genes
  scale = TRUE # we want the data scaled to have unit variance for each gene
)

head(pca$x[, 1:5])

# Save the summary of the PCA results using the `summary()` function
pca_summary <- summary(pca)

# Now access the importance information for the first 5 PCs
pca_summary$importance[, 1:5]


# Make the first two PCs into a data frame for plotting with `ggplot2`
pca_df <- data.frame(pca$x[, 1:2]) %>%
  # Turn samples IDs stored as row names into a column
  tibble::rownames_to_column("refinebio_accession_code") %>%
  # Bring only the variables that we want from the metadata into this data frame
  # here we are going to join by `refinebio_accession_code` values
  dplyr::inner_join(
    dplyr::select(metadata, refinebio_accession_code, refinebio_subject),
    by = "refinebio_accession_code"
  )
  
  
# Make a scatterplot using `ggplot2` functionality
pca_plot <- ggplot(
  pca_df,
  aes(
    x = PC1,
    y = PC2,
    color = refinebio_subject # label points with different colors for each `subgroup`
  )
) +
  geom_point() + # Plot individual points to make a scatterplot
  theme_classic() # Format as a classic-looking plot with no gridlines

# Print out the plot here
pca_plot
  

#tsne
library(Rtsne)
library(ggplot2)

# Perform t-SNE on PC1 and PC2 data
tsne_result <- Rtsne(as.matrix(pca_df[, c("PC1", "PC2")]), check_duplicates = FALSE)

# Extract the t-SNE coordinates
tsne_coords <- tsne_result$Y


# Create a dataframe with t-SNE coordinates
tsne_df <- data.frame(X = tsne_coords[, 1], Y = tsne_coords[, 2],Group = pca_df$refinebio_subject)

# Create a t-SNE plot using ggplot2 and color by Group
tsne_plot <- ggplot(tsne_df, aes(x = X, y = Y, color = factor(Group))) +
  geom_point(size = 3) +  # Adjust the size of points
  labs(title = "t-SNE Plot") +
  theme_minimal()  # Choose a theme (optional)

# Display the t-SNE plot
print(tsne_plot)
